export const icons = {
  search: require("../assets/icons/search.png"),
  home: require("../assets/icons/home.png") || { uri: "https://img.icons8.com/ios/50/000000/home.png" },
  explore: require("../assets/icons/explore.png") || { uri: "https://img.icons8.com/ios/50/000000/compass.png" },
  profile: require("../assets/icons/profile.png") || { uri: "https://img.icons8.com/ios/50/000000/user.png" },
  bike: require("../assets/icons/bike.png") || { uri: "https://img.icons8.com/ios/50/000000/motorcycle.png" },
  location: require("../assets/icons/location.png") || { uri: "https://img.icons8.com/ios/50/000000/marker.png" },
  calendar: require("../assets/icons/calendar.png") || { uri: "https://img.icons8.com/ios/50/000000/calendar.png" },
  money: require("../assets/icons/money.png") || { uri: "https://img.icons8.com/ios/50/000000/money.png" },
  group: require("../assets/icons/group.png") || { uri: "https://img.icons8.com/ios/50/000000/group.png" },
  chat: require("../assets/icons/chat.png") || { uri: "https://img.icons8.com/ios/50/000000/chat.png" },
  back: require("../assets/icons/back.png") || { uri: "https://img.icons8.com/ios/50/000000/back.png" },
  add: require("../assets/icons/add.png") || { uri: "https://img.icons8.com/ios/50/000000/plus.png" },
  like: require("../assets/icons/like.png") || { uri: "https://img.icons8.com/ios/50/000000/like.png" },
  share: require("../assets/icons/share.png") || { uri: "https://img.icons8.com/ios/50/000000/share.png" },
  female: require("../assets/icons/female.png") || { uri: "https://img.icons8.com/ios/50/000000/female.png" },
  map: require("../assets/icons/map.png") || { uri: "https://img.icons8.com/ios/50/000000/map.png" },
  info: require("../assets/icons/info.png") || { uri: "https://img.icons8.com/ios/50/000000/info.png" },
  send: require("../assets/icons/send.png") || { uri: "https://img.icons8.com/ios/50/000000/send.png" },
  down: require("../assets/icons/down.png") || { uri: "https://img.icons8.com/ios/50/000000/down.png" },
  email: require("../assets/icons/email.png") || { uri: "https://img.icons8.com/ios/50/000000/email.png" },
  eye: require("../assets/icons/eye.png") || { uri: "https://img.icons8.com/ios/50/000000/visible.png" },
  eyeOff: require("../assets/icons/eyeOff.png") || { uri: "https://img.icons8.com/ios/50/000000/invisible.png" },
}

